ARG BASE_IMAGE=rtsp-yolo-annotator:deepstream8-pile-amd64
FROM ${BASE_IMAGE}

WORKDIR /app
COPY rtsp_annotator ./rtsp_annotator

RUN python3 -m compileall -q /app/rtsp_annotator

CMD ["python3", "-m", "rtsp_annotator.api", "--config", "/app/config/api.json"]
