ARG BASE_IMAGE=rtsp-yolo-annotator:deepstream8-amd64
FROM ${BASE_IMAGE}

WORKDIR /app

COPY rtsp_annotator/api.py /app/rtsp_annotator/api.py
COPY rtsp_annotator/license_plate.py /app/rtsp_annotator/license_plate.py
COPY rtsp_annotator/stream_manager.py /app/rtsp_annotator/stream_manager.py
COPY rtsp_annotator/shared_stream_manager.py /app/rtsp_annotator/shared_stream_manager.py
COPY rtsp_annotator/deepstream_manager.py /app/rtsp_annotator/deepstream_manager.py
COPY rtsp_annotator/deepstream_worker.py /app/rtsp_annotator/deepstream_worker.py

RUN python3 -m py_compile \
    /app/rtsp_annotator/api.py \
    /app/rtsp_annotator/license_plate.py \
    /app/rtsp_annotator/stream_manager.py \
    /app/rtsp_annotator/shared_stream_manager.py \
    /app/rtsp_annotator/deepstream_manager.py \
    /app/rtsp_annotator/deepstream_worker.py
