logLevel: info

authMethod: http
authHTTPAddress: http://ptz-test-api:8080/internal/mediamtx/auth
authHTTPExclude:
  - action: api
  - action: metrics
  - action: pprof

rtsp: true
rtspTransports: [tcp]
rtspAddress: :8554

paths:
  all_others:
